jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/day01
  username: root
  password: 123456
server:
  port: 80
  servlet:
    path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/day01?useSSL=false
    username: root
    password: 123456
# mybatis 别名扫描
mybatis:
  type-aliases-package: com.hp.pojo
